I'm sorry, but an uncaught exception occurred.

While parsing /home/junior/trabalho/sHoRTcut/esofteacher/game/script.rpy.
ScriptError: Name u'done' is defined twice: at game/script.rpy:57 and game/script.rpy:93.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/junior/renpy-6.17.3-sdk/renpy/bootstrap.py", line 286, in bootstrap
    renpy.main.main()
  File "/home/junior/renpy-6.17.3-sdk/renpy/main.py", line 227, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/home/junior/renpy-6.17.3-sdk/renpy/script.py", line 177, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "/home/junior/renpy-6.17.3-sdk/renpy/script.py", line 441, in load_appropriate_file
    if not self.load_file(dir, fn + source, initcode):
  File "/home/junior/renpy-6.17.3-sdk/renpy/script.py", line 320, in load_file
    self.finish_load(stmts, initcode)
  File "/home/junior/renpy-6.17.3-sdk/renpy/script.py", line 392, in finish_load
    node.filename, node.linenumber))
ScriptError: Name u'done' is defined twice: at game/script.rpy:57 and game/script.rpy:93.

Linux-3.11.0-18-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.17.3.327
 
