I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/supervisorScene.rpy", line 24, in script
  File "game/supervisorScene.rpy", line 24, in python
NameError: name 'lv' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/junior/renpy-6.17.3-sdk/renpy/execution.py", line 294, in run
    node.execute()
  File "/home/junior/renpy-6.17.3-sdk/renpy/ast.py", line 732, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/junior/renpy-6.17.3-sdk/renpy/python.py", line 1358, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/supervisorScene.rpy", line 24, in <module>
    $ stats_frame(nome, lv, hp, php, xalign=.02, yalign=.05)
NameError: name 'lv' is not defined

Linux-3.11.0-19-generic-x86_64-with-debian-wheezy-sid
Ren'Py 6.17.3.327
ESofTeacher 0.0
